# main text of home
name: daniel chen
nickname: dandandives
bio: i cook (and write some code too)

# twitter summary info
description: A blog about technology and stuff related

# if it's an external image, update below for true
# better with square images
external-image: false
picture: assets/images/profile.jpg

# If you want to include your resume, set to true
# and specify source (external or local).
resume: true
resume-external: true
resume-url: https://read.cv/dandandives

url: https://danielchen-pyc.github.io
github-url: https://github.com/danielchen-pyc/

permalink: /:title/

# To enable google analytics, supply your token below
# analytics-google: 'UA-MYANALYTICS'

# To enable piwik tracking, supply your url & site ID below
# analytics-piwik-url: 'piwik.my-host.com'
# analytics-piwik-id: 1

# if you don't want comments in your posts, leave categories empty
# disqus:
#   shortname: mydisqus # enter this from your disqus account
#   categories: [blog, project] # only show disqus for posts that have these categories

# if you don't have any of social below, comment the line
# facebook: myfacebook
# twitter: mytwitter
instagram: dandandives
linkedin: daniel-chen-1a9610196
github: danielchen-pyc
# medium: medium
email: poyuchen@alumni.ubc.ca

authors:
  dandandives:
    name: daniel chen
    bio: i cook (and write some code too)
    external-image: false
    picture: assets/images/profile.jpg

# do you want a larger site? change the option below
# options: [normal, large] | default: normal
# normal = 560px / large = 810px
width: large

collections_dir: content
permalink: /:title/
collections:
  experiences:
    output: true
    permalink: /experiences/:title
  design-teams:
    output: true
    permalink: /designTeams/:title
  tech-projects:
    output: true
    permalink: /techProjects/:title

# if you do/don't need pagination, toggle 'enabled' between true/false below
pagination:
  enabled: true
  sort_reverse: true # display recent posts first
  title: ":title" # Changing this will mess up the header display logic
  per_page: 5
  permalink: "/:num/" # pagination link that will be appended

# about: true
projects: true
blog: true

read-time: true
show-tags: true
related: true

# Display links for next and previous posts for the specified categories
post-advance-links: [blog]

show-author: false
animation: true

# add default values to specific pages or layouts
defaults:
  - scope:
      path: "" # an empty string here means all files in the project
      layout: "post"
    values:
      # setting all post to not hidden by default,
      # can be overridden in the front matter for a specific post
      hidden: false

plugins:
  - jekyll-seo-tag
  - jekyll-gist
  - jekyll-feed
  - jemoji
  - jekyll-admin
  - jekyll-paginate

jekyll-mentions:
  base_url: https://github.com

compress_html:
  ignore:
    envs:
      - development
      - stage

exclude:
  [
    "travis.sh",
    "README.md",
    "Gemfile",
    "Gemfile.lock",
    "FAQ.md",
    "node_modules",
    "vendor",
  ]
